version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "courses-payments-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-th0ssaiqdovt"
s3_prefix = "courses-payments-test"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PaymentDomainHostedZoneId=\"Z03959971PI6LXD3U3GYA\" PaymentDomainName=\"test.payment.jvmperformance.pl\" PaymentCertificateArn=\"arn:aws:acm:eu-central-1:653932013369:certificate/7db121b9-b404-4af6-ad99-e972da300996\" Stage=\"test\" StagePrefix=\"test.\""
image_repositories = []
[prod.deploy.parameters]
stack_name = "courses-payments-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-th0ssaiqdovt"
s3_prefix = "courses-payments-prod"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PaymentDomainHostedZoneId=\"Z03959971PI6LXD3U3GYA\" PaymentDomainName=\"payment.jvmperformance.pl\" PaymentCertificateArn=\"arn:aws:acm:eu-central-1:653932013369:certificate/28abef60-629b-4650-90a1-d0f9e7b0ac59\" Stage=\"prod\" StagePrefix=\"prod.\""
image_repositories = []
