AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  PaymentDomainHostedZoneId: 
    Type: "String"
    Default: "Z03959971PI6LXD3U3GYA"
  PaymentDomainName: 
    Type: "String"
    Default: payment.jvmperformance.pl
  PaymentCertificateArn:
    Type: "String"
    Default: "arn:aws:acm:eu-central-1:653932013369:certificate/5b84c97f-2538-48f2-b62d-9dbf82e78703"

Resources:
  PaymentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: payment/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CourseTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DiscountTable
      Events:
        Payment:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /payment
            Method: get
            RestApiId: !Ref PaymentApiGateway
  ConfirmationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: confirmation/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PaymentTable
      Events:
        Confirmation:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /confirmation
            Method: post
            RestApiId: !Ref PaymentApiGateway
  JsonCoursesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: courses/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CourseTable
      Events:
        Confirmation:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /courses
            Method: get
            RestApiId: !Ref PaymentApiGateway
  PaymentTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: payments
      BillingMode: PAY_PER_REQUEST   
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
  CourseTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: courses
      BillingMode: PAY_PER_REQUEST   
      AttributeDefinitions: 
        - AttributeName: course_name
          AttributeType: S
      KeySchema: 
        - AttributeName: course_name
          KeyType: HASH
  DiscountTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: discounts
      BillingMode: PAY_PER_REQUEST   
      AttributeDefinitions: 
        - AttributeName: discount_code
          AttributeType: S
      KeySchema: 
        - AttributeName: discount_code
          KeyType: HASH
  PaymentApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Domain:
        CertificateArn: !Ref PaymentCertificateArn
        DomainName: !Join
          - ''
          - - 'api.'
            - !Ref PaymentDomainName
        Route53:
          HostedZoneId: !Ref PaymentDomainHostedZoneId
  
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PaymentGatewayApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${PaymentApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/payment/"
  PaymentFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PaymentFunction.Arn
  PaymentFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PaymentFunctionRole.Arn
